### ISSUE TITLE
Buggy dirt/grass texture.

### ISSUE THREAD

**Issue by DemonicSavage** [jManAscending/JPBR32x#1]
![2022-08-21_11 48 10](https://user-images.githubusercontent.com/1365501/185796860-6edc2621-fcf2-4104-9498-0720499568a1.png)

I get this while using JPBR32x, with SEUS and Complementary shaders.

**Comment by jManAscending** [comment]
Fixed in v1.2.1

**Comment by lunananananananana** [comment]
It's a lot more subtle, but it's still broken in 1.3: (Complementary v4.6 on the extreme preset)

![2022-11-06_14 18 47](https://user-images.githubusercontent.com/29987831/200173015-b66a119c-5865-4891-b4a0-45a00e629e9d.png)
